<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ProductItemRequest {

  static $swaggerTypes = array(    
    'id' => 'int',
    'product_item_id' => 'int',
    'is_visible_on_hosted_page' => 'bool',
    'description' => 'string',
    'charge_model' => 'string',
    'name' => 'string',
    'product_item_children' => 'array<ProductItemRequest>',
    'unit_name' => 'string',
    'metered_prices' => 'array<ProductMeteredPriceRequest>',
    'item_type' => 'string'   
    );


    /**
     * 
     */
	 public $id;// int


    /**
     * 
     */
	 public $product_item_id;// int


    /**
     * 
     */
	 public $is_visible_on_hosted_page;// bool


    /**
     * 
     */
	 public $description;// string


    /**
     * 
     */
	 public $charge_model;// string


    /**
     * 
     */
	 public $name;// string


    /**
     * 
     */
	 public $product_item_children =  array();// array<ProductItemRequest>


    /**
     * 
     */
	 public $unit_name;// string


    /**
     * 
     */
	 public $metered_prices =  array();// array<ProductMeteredPriceRequest>


    /**
     * 
     */
	 public $item_type;// string


}

?>