<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SubscriptionResponse {

  static $swaggerTypes = array(    
    'signup_date' => 'string',
    'product_id' => 'int',
    'service_result' => 'ServiceResult',
    'next_product' => 'ProductResponse',
    'customer' => 'CustomerResponse',
    'next_assesment' => 'string',
    'cancellation_details' => 'string',
    'billing_address_id' => 'int',
    'currency' => 'Currency',
    'product_pricing_plan' => 'PricingPlanResponse',
    'id' => 'int',
    'end_date' => 'string',
    'credit_card' => 'CreditCardResponse',
    'current_ballance' => 'float',
    'revenue' => 'float',
    'status' => 'string',
    'is_cancelled_at_end_of_period' => 'bool',
    'next_product_pricing_plan' => 'PricingPlanResponse',
    'cancellation_date' => 'string',
    'product' => 'ProductResponse',
    'credit_card_id' => 'int',
    'is_trial' => 'bool',
    'pricing_plan_id' => 'int',
    'start_date' => 'string',
    'customer_id' => 'int',
    'billing_address' => 'AddressResponse'   
    );


    /**
     * 
     */
	 public $signup_date;// string


    /**
     * 
     */
	 public $product_id;// int


    /**
     * 
     */
	 public $service_result;// ServiceResult


    /**
     * 
     */
	 public $next_product;// ProductResponse


    /**
     * 
     */
	 public $customer;// CustomerResponse


    /**
     * 
     */
	 public $next_assesment;// string


    /**
     * 
     */
	 public $cancellation_details;// string


    /**
     * 
     */
	 public $billing_address_id;// int


    /**
     * 
     */
	 public $currency;// Currency


    /**
     * 
     */
	 public $product_pricing_plan;// PricingPlanResponse


    /**
     * 
     */
	 public $id;// int


    /**
     * 
     */
	 public $end_date;// string


    /**
     * 
     */
	 public $credit_card;// CreditCardResponse


    /**
     * 
     */
	 public $current_ballance;// float


    /**
     * 
     */
	 public $revenue;// float


    /**
     * 
     */
	 public $status;// string


    /**
     * 
     */
	 public $is_cancelled_at_end_of_period;// bool


    /**
     * 
     */
	 public $next_product_pricing_plan;// PricingPlanResponse


    /**
     * 
     */
	 public $cancellation_date;// string


    /**
     * 
     */
	 public $product;// ProductResponse


    /**
     * 
     */
	 public $credit_card_id;// int


    /**
     * 
     */
	 public $is_trial;// bool


    /**
     * 
     */
	 public $pricing_plan_id;// int


    /**
     * 
     */
	 public $start_date;// string


    /**
     * 
     */
	 public $customer_id;// int


    /**
     * 
     */
	 public $billing_address;// AddressResponse


}

?>