<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TransactionResponse {

  static $swaggerTypes = array(    
    'gateway_response_message' => 'string',
    'subscription_id' => 'int',
    'transaction_type' => 'string',
    'gateway_raw_response' => 'string',
    'transaction_date' => 'string',
    'settlement_attempts_count' => 'int',
    'currency' => 'string',
    'purchase_order_reference' => 'string',
    'amount' => 'float',
    'id' => 'int',
    'last_settlement_attempt_date' => 'string',
    'transaction_status' => 'string',
    'refunded' => 'float',
    'details' => 'string',
    'gateway_raw_request' => 'string',
    'gateway_transaction_id' => 'string',
    'subscription_balance' => 'float',
    'gateway_response_code' => 'string',
    'gateway_response_description' => 'string',
    'gateway_status' => 'string',
    'gateway_ref_transaction_id' => 'string',
    'gateway_settle_date' => 'string'   
    );


    /**
     * 
     */
	 public $gateway_response_message;// string


    /**
     * 
     */
	 public $subscription_id;// int


    /**
     * 
     */
	 public $transaction_type;// string


    /**
     * 
     */
	 public $gateway_raw_response;// string


    /**
     * 
     */
	 public $transaction_date;// string


    /**
     * 
     */
	 public $settlement_attempts_count;// int


    /**
     * 
     */
	 public $currency;// string


    /**
     * 
     */
	 public $purchase_order_reference;// string


    /**
     * 
     */
	 public $amount;// float


    /**
     * 
     */
	 public $id;// int


    /**
     * 
     */
	 public $last_settlement_attempt_date;// string


    /**
     * 
     */
	 public $transaction_status;// string


    /**
     * 
     */
	 public $refunded;// float


    /**
     * 
     */
	 public $details;// string


    /**
     * 
     */
	 public $gateway_raw_request;// string


    /**
     * 
     */
	 public $gateway_transaction_id;// string


    /**
     * 
     */
	 public $subscription_balance;// float


    /**
     * 
     */
	 public $gateway_response_code;// string


    /**
     * 
     */
	 public $gateway_response_description;// string


    /**
     * 
     */
	 public $gateway_status;// string


    /**
     * 
     */
	 public $gateway_ref_transaction_id;// string


    /**
     * 
     */
	 public $gateway_settle_date;// string


}

?>