<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class AddressResponse {

  static $swaggerTypes = array(    
    'fax_number' => 'string',
    'state_province' => 'string',
    'phone_number' => 'string',
    'created_on' => 'string',
    'address1' => 'string',
    'address2' => 'string',
    'country' => 'string',
    'city' => 'string',
    'id' => 'int',
    'first_name' => 'string',
    'email' => 'string',
    'company' => 'string',
    'last_name' => 'string',
    'updated_on' => 'string',
    'zip_postal_code' => 'string',
    'customer_id' => 'int'   
    );



    /**
     * 
     */
	 public $fax_number;// string



    /**
     * 
     */
	 public $state_province;// string



    /**
     * 
     */
	 public $phone_number;// string



    /**
     * 
     */
	 public $created_on;// string



    /**
     * 
     */
	 public $address1;// string



    /**
     * 
     */
	 public $address2;// string



    /**
     * 
     */
	 public $country;// string



    /**
     * 
     */
	 public $city;// string



    /**
     * 
     */
	 public $id;// int



    /**
     * 
     */
	 public $first_name;// string



    /**
     * 
     */
	 public $email;// string



    /**
     * 
     */
	 public $company;// string



    /**
     * 
     */
	 public $last_name;// string



    /**
     * 
     */
	 public $updated_on;// string



    /**
     * 
     */
	 public $zip_postal_code;// string



    /**
     * 
     */
	 public $customer_id;// int


}

?>