<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Address {

  static $swaggerTypes = array(    
    'UpdatedOn' => 'string',
    'PhoneNumber' => 'string',
    'StateProvinceId' => 'int',
    'LastName' => 'string',
    'City' => 'string',
    'Email' => 'string',
    'CustomerId' => 'int',
    'Address2' => 'string',
    'FaxNumber' => 'string',
    'Address1' => 'string',
    'CreatedOn' => 'string',
    'CountryId' => 'int',
    'IsBillingAddress' => 'bool',
    'FirstName' => 'string',
    'Id' => 'int',
    'Company' => 'string',
    'ZipPostalCode' => 'string'   
    );


    /**
     * 
     */
	 public $UpdatedOn;// string


    /**
     * 
     */
	 public $PhoneNumber;// string


    /**
     * 
     */
	 public $StateProvinceId;// int


    /**
     * 
     */
	 public $LastName;// string


    /**
     * 
     */
	 public $City;// string


    /**
     * 
     */
	 public $Email;// string


    /**
     * 
     */
	 public $CustomerId;// int


    /**
     * 
     */
	 public $Address2;// string


    /**
     * 
     */
	 public $FaxNumber;// string


    /**
     * 
     */
	 public $Address1;// string


    /**
     * 
     */
	 public $CreatedOn;// string


    /**
     * 
     */
	 public $CountryId;// int


    /**
     * 
     */
	 public $IsBillingAddress;// bool


    /**
     * 
     */
	 public $FirstName;// string


    /**
     * 
     */
	 public $Id;// int


    /**
     * 
     */
	 public $Company;// string


    /**
     * 
     */
	 public $ZipPostalCode;// string


}

?>