<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Country {

  static $swaggerTypes = array(    
    'NumericIsoCode' => 'int',
    'Fips' => 'string',
    'DisplayOrder' => 'int',
    'Tld' => 'string',
    'Area' => 'int',
    'Capital' => 'string',
    'Geonameid' => 'int',
    'PostalCodeRegex' => 'string',
    'EquivalentFipsCode' => 'string',
    'CurrencyCode' => 'string',
    'Languages' => 'string',
    'Name' => 'string',
    'ThreeLetterIsoCode' => 'string',
    'CurrencyName' => 'string',
    'PostalCodeFormat' => 'string',
    'Neighbours' => 'string',
    'Population' => 'int',
    'Id' => 'int',
    'Continent' => 'string',
    'TwoLetterIsoCode' => 'string'   
    );



    /**
     * 
     */
	 public $NumericIsoCode;// int



    /**
     * 
     */
	 public $Fips;// string



    /**
     * 
     */
	 public $DisplayOrder;// int



    /**
     * 
     */
	 public $Tld;// string



    /**
     * 
     */
	 public $Area;// int



    /**
     * 
     */
	 public $Capital;// string



    /**
     * 
     */
	 public $Geonameid;// int



    /**
     * 
     */
	 public $PostalCodeRegex;// string



    /**
     * 
     */
	 public $EquivalentFipsCode;// string



    /**
     * 
     */
	 public $CurrencyCode;// string



    /**
     * 
     */
	 public $Languages;// string



    /**
     * 
     */
	 public $Name;// string



    /**
     * 
     */
	 public $ThreeLetterIsoCode;// string



    /**
     * 
     */
	 public $CurrencyName;// string



    /**
     * 
     */
	 public $PostalCodeFormat;// string



    /**
     * 
     */
	 public $Neighbours;// string



    /**
     * 
     */
	 public $Population;// int



    /**
     * 
     */
	 public $Id;// int



    /**
     * 
     */
	 public $Continent;// string



    /**
     * 
     */
	 public $TwoLetterIsoCode;// string


}

?>