<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class CustomerRequest {

  static $swaggerTypes = array(    
    'shipping_address' => 'AddressRequest',
    'first_name' => 'string',
    'phone' => 'string',
    'email' => 'string',
    'company' => 'string',
    'shipping_address_id' => 'int',
    'is_shipping_address_same_to_billing' => 'bool',
    'last_name' => 'string',
    'reference' => 'string'   
    );


    /**
     * 
     */
	 public $shipping_address;// AddressRequest


    /**
     * 
     */
	 public $first_name;// string


    /**
     * 
     */
	 public $phone;// string


    /**
     * 
     */
	 public $email;// string


    /**
     * 
     */
	 public $company;// string


    /**
     * 
     */
	 public $shipping_address_id;// int


    /**
     * 
     */
	 public $is_shipping_address_same_to_billing;// bool


    /**
     * 
     */
	 public $last_name;// string


    /**
     * 
     */
	 public $reference;// string


}

?>