<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class PricingPlanResponse {

  static $swaggerTypes = array(    
    'id' => 'int',
    'product_id' => 'int',
    'trial_period_duration_days' => 'int',
    'trial_period_charge' => 'float',
    'name' => 'string',
    'upfront_charge' => 'float',
    'product_items' => 'array<ProductItemResponse>',
    'pricing_plan_payment_schedules' => 'array<ProductPricingPlanPaymentScheduleResponse>',
    'currency_code' => 'string'   
    );



    /**
     * 
     */
	 public $id;// int



    /**
     * 
     */
	 public $product_id;// int



    /**
     * 
     */
	 public $trial_period_duration_days;// int



    /**
     * 
     */
	 public $trial_period_charge;// float



    /**
     * 
     */
	 public $name;// string



    /**
     * 
     */
	 public $upfront_charge;// float



    /**
     * 
     */
	 public $product_items =  array();// array<ProductItemResponse>



    /**
     * 
     */
	 public $pricing_plan_payment_schedules =  array();// array<ProductPricingPlanPaymentScheduleResponse>



    /**
     * 
     */
	 public $currency_code;// string


}

?>