<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ProductRequest {

  static $swaggerTypes = array(    
    'id' => 'int',
    'is_billing_address_at_signup_required' => 'string',
    'is_credit_card_at_signup_required' => 'string',
    'pricing_plans' => 'array<PricingPlanRequest>',
    'description' => 'string',
    'accounting_code' => 'string',
    'api_reference1' => 'string',
    'name' => 'string',
    'product_family_id' => 'int'   
    );



    /**
     * 
     */
	 public $id;// int



    /**
     * 
     */
	 public $is_billing_address_at_signup_required;// string



    /**
     * 
     */
	 public $is_credit_card_at_signup_required;// string



    /**
     * 
     */
	 public $pricing_plans =  array();// array<PricingPlanRequest>



    /**
     * 
     */
	 public $description;// string



    /**
     * 
     */
	 public $accounting_code;// string



    /**
     * 
     */
	 public $api_reference1;// string



    /**
     * 
     */
	 public $name;// string



    /**
     * 
     */
	 public $product_family_id;// int


}

?>