<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TestData {

  static $swaggerTypes = array(    
    'addressList' => 'Array<Address>',
    'stateProvinceList' => 'Array<StateProvince>',
    'countryList' => 'Array<Country>',
    'addressRequestList' => 'Array<AddressRequest>',
    'customerResponseList' => 'Array<CustomerResponse>',
    'creditCardResponseList' => 'Array<CreditCardResponse>',
    'customerRequestList' => 'Array<CustomerRequest>',
    'creditCardRequestList' => 'Array<CreditCardRequest>',
    'addressResponseList' => 'Array<AddressResponse>',
    'productResponseList' => 'Array<ProductResponse>',
    'pricingPlanResponseList' => 'Array<PricingPlanResponse>',
    'productFamilyResponseList' => 'Array<ProductFamilyResponse>',
    'productItemRequestList' => 'Array<ProductItemRequest>',
    'productPricingPlanPaymentScheduleRequestList' => 'Array<ProductPricingPlanPaymentScheduleRequest>',
    'productItemResponseList' => 'Array<ProductItemResponse>',
    'productMeteredPriceRequestList' => 'Array<ProductMeteredPriceRequest>',
    'productRequestList' => 'Array<ProductRequest>',
    'productFamilyRequestList' => 'Array<ProductFamilyRequest>',
    'productMeteredPriceResponseList' => 'Array<ProductMeteredPriceResponse>',
    'pricingPlanRequestList' => 'Array<PricingPlanRequest>',
    'productPricingPlanPaymentScheduleResponseList' => 'Array<ProductPricingPlanPaymentScheduleResponse>',
    'siteSummaryList' => 'Array<SiteSummary>',
    'reportIntValueItemList' => 'Array<ReportIntValueItem>',
    'activeSubscriptionsCountResponseList' => 'Array<ActiveSubscriptionsCountResponse>',
    'totalSubscribersCountResponseList' => 'Array<TotalSubscribersCountResponse>',
    'revenueAmountList' => 'Array<RevenueAmount>',
    'productsSignupsList' => 'Array<ProductsSignups>',
    'productsRevenuesList' => 'Array<ProductsRevenues>',
    'reportDecimalValueItemList' => 'Array<ReportDecimalValueItem>',
    'todayNewSubscribersCountResponseList' => 'Array<TodayNewSubscribersCountResponse>',
    'statementList' => 'Array<Statement>',
    'statementDetailList' => 'Array<StatementDetail>',
    'subscriptionRequestList' => 'Array<SubscriptionRequest>',
    'subscriptionResponseList' => 'Array<SubscriptionResponse>',
    'serviceResultList' => 'Array<ServiceResult>',
    'currencyList' => 'Array<Currency>',
    'cancellationRequestList' => 'Array<CancellationRequest>',
    'subscriptionItemHistoryResponseList' => 'Array<SubscriptionItemHistoryResponse>',
    'subscriptionItemResponseList' => 'Array<SubscriptionItemResponse>',
    'transactionResponseList' => 'Array<TransactionResponse>',
    'subscriptionItemRequestList' => 'Array<SubscriptionItemRequest>',
    'chargeRequestList' => 'Array<ChargeRequest>',
    'eventDataList' => 'Array<EventData>'   
    );


    /**
     * 
     */
	 public $addressList;// Array<Address>


    /**
     * 
     */
	 public $stateProvinceList;// Array<StateProvince>


    /**
     * 
     */
	 public $countryList;// Array<Country>


    /**
     * 
     */
	 public $addressRequestList;// Array<AddressRequest>


    /**
     * 
     */
	 public $customerResponseList;// Array<CustomerResponse>


    /**
     * 
     */
	 public $creditCardResponseList;// Array<CreditCardResponse>


    /**
     * 
     */
	 public $customerRequestList;// Array<CustomerRequest>


    /**
     * 
     */
	 public $creditCardRequestList;// Array<CreditCardRequest>


    /**
     * 
     */
	 public $addressResponseList;// Array<AddressResponse>


    /**
     * 
     */
	 public $productResponseList;// Array<ProductResponse>


    /**
     * 
     */
	 public $pricingPlanResponseList;// Array<PricingPlanResponse>


    /**
     * 
     */
	 public $productFamilyResponseList;// Array<ProductFamilyResponse>


    /**
     * 
     */
	 public $productItemRequestList;// Array<ProductItemRequest>


    /**
     * 
     */
	 public $productPricingPlanPaymentScheduleRequestList;// Array<ProductPricingPlanPaymentScheduleRequest>


    /**
     * 
     */
	 public $productItemResponseList;// Array<ProductItemResponse>


    /**
     * 
     */
	 public $productMeteredPriceRequestList;// Array<ProductMeteredPriceRequest>


    /**
     * 
     */
	 public $productRequestList;// Array<ProductRequest>


    /**
     * 
     */
	 public $productFamilyRequestList;// Array<ProductFamilyRequest>


    /**
     * 
     */
	 public $productMeteredPriceResponseList;// Array<ProductMeteredPriceResponse>


    /**
     * 
     */
	 public $pricingPlanRequestList;// Array<PricingPlanRequest>


    /**
     * 
     */
	 public $productPricingPlanPaymentScheduleResponseList;// Array<ProductPricingPlanPaymentScheduleResponse>


    /**
     * 
     */
	 public $siteSummaryList;// Array<SiteSummary>


    /**
     * 
     */
	 public $reportIntValueItemList;// Array<ReportIntValueItem>


    /**
     * 
     */
	 public $activeSubscriptionsCountResponseList;// Array<ActiveSubscriptionsCountResponse>


    /**
     * 
     */
	 public $totalSubscribersCountResponseList;// Array<TotalSubscribersCountResponse>


    /**
     * 
     */
	 public $revenueAmountList;// Array<RevenueAmount>


    /**
     * 
     */
	 public $productsSignupsList;// Array<ProductsSignups>


    /**
     * 
     */
	 public $productsRevenuesList;// Array<ProductsRevenues>


    /**
     * 
     */
	 public $reportDecimalValueItemList;// Array<ReportDecimalValueItem>


    /**
     * 
     */
	 public $todayNewSubscribersCountResponseList;// Array<TodayNewSubscribersCountResponse>


    /**
     * 
     */
	 public $statementList;// Array<Statement>


    /**
     * 
     */
	 public $statementDetailList;// Array<StatementDetail>


    /**
     * 
     */
	 public $subscriptionRequestList;// Array<SubscriptionRequest>


    /**
     * 
     */
	 public $subscriptionResponseList;// Array<SubscriptionResponse>


    /**
     * 
     */
	 public $serviceResultList;// Array<ServiceResult>


    /**
     * 
     */
	 public $currencyList;// Array<Currency>


    /**
     * 
     */
	 public $cancellationRequestList;// Array<CancellationRequest>


    /**
     * 
     */
	 public $subscriptionItemHistoryResponseList;// Array<SubscriptionItemHistoryResponse>


    /**
     * 
     */
	 public $subscriptionItemResponseList;// Array<SubscriptionItemResponse>


    /**
     * 
     */
	 public $transactionResponseList;// Array<TransactionResponse>


    /**
     * 
     */
	 public $subscriptionItemRequestList;// Array<SubscriptionItemRequest>


    /**
     * 
     */
	 public $chargeRequestList;// Array<ChargeRequest>


    /**
     * 
     */
	 public $eventDataList;// Array<EventData>


}

?>