<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TestData {

  static $swaggerTypes = array(    
    'applicationResponseList' => 'Array<ApplicationResponse>',
    'applicationPlanList' => 'Array<ApplicationPlan>',
    'applicationInCompanyResponseList' => 'Array<ApplicationInCompanyResponse>',
    'companyInfoRequestList' => 'Array<CompanyInfoRequest>',
    'companyInfoResponseList' => 'Array<CompanyInfoResponse>',
    'setActiveMarketingPlanResponseList' => 'Array<SetActiveMarketingPlanResponse>',
    'eventResponseList' => 'Array<EventResponse>',
    'eventParamList' => 'Array<EventParam>',
    'settingRequestList' => 'Array<SettingRequest>',
    'settingResponseList' => 'Array<SettingResponse>',
    'siteResponseList' => 'Array<SiteResponse>',
    'siteRequestList' => 'Array<SiteRequest>',
    'userResponseList' => 'Array<UserResponse>',
    'userApiKeysResponseList' => 'Array<UserApiKeysResponse>',
    'userRequestList' => 'Array<UserRequest>'   
    );


    /**
     * 
     */
	 public $applicationResponseList;// Array<ApplicationResponse>


    /**
     * 
     */
	 public $applicationPlanList;// Array<ApplicationPlan>


    /**
     * 
     */
	 public $applicationInCompanyResponseList;// Array<ApplicationInCompanyResponse>


    /**
     * 
     */
	 public $companyInfoRequestList;// Array<CompanyInfoRequest>


    /**
     * 
     */
	 public $companyInfoResponseList;// Array<CompanyInfoResponse>


    /**
     * 
     */
	 public $setActiveMarketingPlanResponseList;// Array<SetActiveMarketingPlanResponse>


    /**
     * 
     */
	 public $eventResponseList;// Array<EventResponse>


    /**
     * 
     */
	 public $eventParamList;// Array<EventParam>


    /**
     * 
     */
	 public $settingRequestList;// Array<SettingRequest>


    /**
     * 
     */
	 public $settingResponseList;// Array<SettingResponse>


    /**
     * 
     */
	 public $siteResponseList;// Array<SiteResponse>


    /**
     * 
     */
	 public $siteRequestList;// Array<SiteRequest>


    /**
     * 
     */
	 public $userResponseList;// Array<UserResponse>


    /**
     * 
     */
	 public $userApiKeysResponseList;// Array<UserApiKeysResponse>


    /**
     * 
     */
	 public $userRequestList;// Array<UserRequest>


}

?>