<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
 
/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class UserRequest {

  static $swaggerTypes = array(    
    'user_roles' => 'string',
    'password' => 'string',
    'deleted' => 'bool',
    'is_subscribed_to_newsletter' => 'bool',
    'country' => 'string',
    'currency' => 'string',
    'first_name' => 'string',
    'timezone' => 'string',
    'googleapps_user_name' => 'string',
    'email' => 'string',
    'last_name' => 'string',
    'active' => 'bool',
    'yahoo_user_name' => 'string',
    'facebook_id' => 'string',
    'culture' => 'string'   
    );


    /**
     * 
     */
	 public $user_roles;// string


    /**
     * 
     */
	 public $password;// string


    /**
     * 
     */
	 public $deleted;// bool


    /**
     * 
     */
	 public $is_subscribed_to_newsletter;// bool


    /**
     * 
     */
	 public $country;// string


    /**
     * 
     */
	 public $currency;// string


    /**
     * 
     */
	 public $first_name;// string


    /**
     * 
     */
	 public $timezone;// string


    /**
     * 
     */
	 public $googleapps_user_name;// string


    /**
     * 
     */
	 public $email;// string


    /**
     * 
     */
	 public $last_name;// string


    /**
     * 
     */
	 public $active;// bool


    /**
     * 
     */
	 public $yahoo_user_name;// string


    /**
     * 
     */
	 public $facebook_id;// string


    /**
     * 
     */
	 public $culture;// string


}

?>